version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-postgres.properties
    image: conductor:server
    container_name: conductor-server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8000:8080
      - 5001:5000
    healthcheck:
      test: [ "CMD", "curl","-I" ,"-XGET", "http://localhost:8000/health" ]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - conductor-postgres:postgresdb
    depends_on:
      conductor-postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=conductor
      - POSTGRES_PASSWORD=conductor
    volumes:
      - ./../../conductor-data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - 6432:5432
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"



networks:
  internal:
